version: "3"

services:

  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      docker_network:
        ipv4_address: 172.20.0.10

  web-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: web-python
    restart: always
    environment:
      DB_HOST: db-mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    networks:
      docker_network:
        ipv4_address: 172.20.0.5
    depends_on:
      - db-mysql 

  reverse-proxy:
    image: haproxy:2.4
    container_name: reverse-proxy
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
    networks:
      - docker_network
    depends_on:
      - web-python

  ingress-proxy:
    image: nginx:latest
    container_name: ingress-proxy
    restart: always
    network_mode: host
    volumes:
      - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw

networks:
  docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
