FROM python:3.12-slim AS builder

#  Ваш код здесь #

## Рабочая директория
WORKDIR /app

#Установка компилятора gcc
RUN apt-get update && apt-get install -y --no-install-recommends gcc python3-dev

###RUN python -m venv /app/venv
###ENV PATH="/app/venv/bin:$PATH"

## Копируем всё содержимое директории в рабочую директорию (чтобы не копировать по отдельным файлам)
COPY requirements.txt ./

## Устанавливаем зависимости
RUN pip install --user --no-cache-dir -r requirements.txt

FROM python:3.12-slim AS worker

## Рабочая директория
WORKDIR /app

###RUN addgroup --system python && \
###    adduser --system --disabled-password  --ingroup python python && chown python:python /app
###USER python

# Копируем установленные пакеты из builder и исходный файл проекта
COPY --from=builder /root/.local /root/.local
COPY . .

# Обновляем PATH, чтобы uvicorn был доступен
###ENV PATH="/app/venv/bin:$PATH"
ENV PATH=/root/.local/bin:$PATH

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
