FROM python:3.12-slim as builder

#  Ваш код здесь #

## Рабочая директория
WORKDIR /app

#Установка компилятора gcc
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

## Копируем всё содержимое директории в рабочую директорию (чтобы не копировать по отдельным файлам)
COPY requirements.txt ./

## Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.12-slim as worker

## Рабочая директория
WORKDIR /app

RUN addgroup --system python && \
    adduser --system --disabled-password  --ingroup python python && chown python:python /app
USER python

COPY --chown=python:python --from=builder /app/venv ./venv
COPY --chown=python:python . .

ENV PATH="/app/venv/bin:$PATH"

EXPOSE 5000

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
