FROM python:3.12-slim as builder

#  Ваш код здесь #

## Рабочая директория
WORKDIR /work

#Установка компилятора gcc
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

RUN python -m venv /work/venv
ENV PATH="/work/venv/bin:$PATH"

## Копируем всё содержимое директории в рабочую директорию (чтобы не копировать по отдельным файлам)
COPY requirements.txt ./

## Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.12-slim as worker

## Рабочая директория
WORKDIR /work

RUN addgroup --system python && \
    adduser --system --disabled-password  --ingroup python python && chown python:python /work
USER python

COPY --chown=python:python --from=builder /work/venv ./venv
COPY --chown=python:python . .

ENV PATH="/work/venv/bin:$PATH"

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:work", "--host", "0.0.0.0", "--port", "5000"]
